import 'package:flutter/material.dart';
import 'package:flutterapp/car_appapp/generatedhome_screenwidget1/generated/GeneratedFrameWidget1.dart';
import 'package:flutterapp/car_appapp/generatedhome_screenwidget1/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/car_appapp/generatedhome_screenwidget1/generated/GeneratedReptabWidget2.dart';
import 'package:flutterapp/car_appapp/generatedhome_screenwidget1/generated/GeneratedForYouWidget1.dart';
import 'package:flutterapp/car_appapp/generatedhome_screenwidget1/generated/GeneratedEllipse48Widget1.dart';
import 'package:flutterapp/car_appapp/generatedhome_screenwidget1/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/car_appapp/generatedhome_screenwidget1/generated/GeneratedStatusbarWidget10.dart';
import 'package:flutterapp/car_appapp/generatedhome_screenwidget1/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/car_appapp/generatedhome_screenwidget1/generated/GeneratedReadMoreWidget4.dart';
import 'package:flutterapp/car_appapp/generatedhome_screenwidget1/generated/GeneratedRecentlyreadWidget1.dart';
import 'package:flutterapp/car_appapp/generatedhome_screenwidget1/generated/GeneratedExploreWidget1.dart';
import 'package:flutterapp/car_appapp/generatedhome_screenwidget1/generated/GeneratedMenubarWidget1.dart';
import 'package:flutterapp/car_appapp/generatedhome_screenwidget1/generated/GeneratedLine6Widget1.dart';

/* Frame home_screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHome_screenWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1102.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 812.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 247, 247, 247),
                                    ),
                                  ),
                                  Positioned(
                                    left: 17.9970703125,
                                    top: 83.5,
                                    right: null,
                                    bottom: null,
                                    width: 81.0,
                                    height: 1.0,
                                    child: GeneratedLine6Widget1(),
                                  ),
                                  Positioned(
                                    left: 13.0,
                                    top: 135.67144775390625,
                                    right: null,
                                    bottom: null,
                                    width: 159.0,
                                    height: 112.39659118652344,
                                    child: GeneratedRectangle6Widget1(),
                                  ),
                                  Positioned(
                                    left: 24.9990234375,
                                    top: 134.0,
                                    right: null,
                                    bottom: null,
                                    width: 154.99998474121094,
                                    height: 110.09385681152344,
                                    child: GeneratedRectangle7Widget1(),
                                  ),
                                  Positioned(
                                    left: 185.0,
                                    top: 152.0,
                                    right: null,
                                    bottom: null,
                                    width: 142.0,
                                    height: 58.0,
                                    child: GeneratedGroup1Widget1(),
                                  ),
                                  Positioned(
                                    left: 188.0,
                                    top: 210.0,
                                    right: null,
                                    bottom: null,
                                    width: 112.0,
                                    height: 25.77777099609375,
                                    child: GeneratedRecentlyreadWidget1(),
                                  ),
                                  Positioned(
                                    left: 300.0,
                                    top: 749.0,
                                    right: null,
                                    bottom: null,
                                    width: 65.0,
                                    height: 17.0,
                                    child: GeneratedReadMoreWidget4(),
                                  ),
                                  Positioned(
                                    left: -17.0,
                                    top: 268.0,
                                    right: null,
                                    bottom: null,
                                    width: 482.9999084472656,
                                    height: 834.0,
                                    child: GeneratedReptabWidget2(),
                                  ),
                                  Positioned(
                                    left: 7.0,
                                    top: 794.0,
                                    right: null,
                                    bottom: null,
                                    width: 828.0,
                                    height: 150.0,
                                    child: GeneratedFrameWidget1(),
                                  ),
                                  Positioned(
                                    left: 322.0,
                                    top: 53.0,
                                    right: null,
                                    bottom: null,
                                    width: 37.0,
                                    height: 37.0,
                                    child: GeneratedEllipse48Widget1(),
                                  ),
                                  Positioned(
                                    left: 121.0,
                                    top: 53.0,
                                    right: null,
                                    bottom: null,
                                    width: 67.0,
                                    height: 31.0,
                                    child: GeneratedExploreWidget1(),
                                  ),
                                  Positioned(
                                    left: 18.0,
                                    top: 50.0,
                                    right: null,
                                    bottom: null,
                                    width: 84.0,
                                    height: 35.0,
                                    child: GeneratedForYouWidget1(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 20.0,
              top: 12.0,
              right: null,
              bottom: null,
              width: 340.0467834472656,
              height: 24.0,
              child: GeneratedStatusbarWidget10(),
            ),
            Positioned(
              left: 0.0,
              top: 740.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 77.0,
              child: GeneratedMenubarWidget1(),
            )
          ]),
    ));
  }
}
