import 'package:flutter/material.dart';
import 'package:flutterapp/car_appapp/generatedsearchwidget1/generated/GeneratedBuuton2Widget2.dart';
import 'package:flutterapp/car_appapp/generatedsearchwidget1/generated/GeneratedStatusbarWidget8.dart';
import 'package:flutterapp/car_appapp/generatedsearchwidget1/generated/GeneratedBuuton2Widget.dart';
import 'package:flutterapp/car_appapp/generatedsearchwidget1/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/car_appapp/generatedsearchwidget1/generated/GeneratedSearch_toolWidget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/car_appapp/generatedsearchwidget1/generated/GeneratedBuuton2Widget3.dart';
import 'package:flutterapp/car_appapp/generatedsearchwidget1/generated/GeneratedBuuton2Widget4.dart';
import 'package:flutterapp/car_appapp/generatedsearchwidget1/generated/GeneratedIphonekeyboard1Widget2.dart';
import 'package:flutterapp/car_appapp/generatedsearchwidget1/generated/GeneratedBuuton2Widget1.dart';

/* Frame search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Container(
                width: 375.0,
                height: 812.0,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    overflow: Overflow.visible,
                    children: [
                      ClipRRect(
                        borderRadius: BorderRadius.zero,
                        child: Container(
                          color: Color.fromARGB(255, 247, 247, 247),
                        ),
                      ),
                      Positioned(
                        left: -4.0,
                        top: -52.0,
                        right: null,
                        bottom: null,
                        width: 385.0,
                        height: 244.0,
                        child: GeneratedRectangle19Widget(),
                      ),
                      Positioned(
                        left: -1.0,
                        top: 524.0,
                        right: null,
                        bottom: null,
                        width: 376.0,
                        height: 288.3575439453125,
                        child: GeneratedIphonekeyboard1Widget2(),
                      )
                    ]),
              ),
              Positioned(
                left: 10.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 32.0,
                child: GeneratedSearch_toolWidget(),
              ),
              Positioned(
                left: 11.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 27.286819458007812,
                child: GeneratedBuuton2Widget(),
              ),
              Positioned(
                left: 134.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 27.286819458007812,
                child: GeneratedBuuton2Widget1(),
              ),
              Positioned(
                left: 257.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 27.286819458007812,
                child: GeneratedBuuton2Widget2(),
              ),
              Positioned(
                left: 42.0,
                top: 151.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 27.286819458007812,
                child: GeneratedBuuton2Widget3(),
              ),
              Positioned(
                left: 163.0,
                top: 151.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 27.286819458007812,
                child: GeneratedBuuton2Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 340.0467834472656,
                height: 24.0,
                child: GeneratedStatusbarWidget8(),
              )
            ]),
      ),
    ));
  }
}
