import 'package:flutter/material.dart';
import 'package:flutterapp/car_appapp/generatedlogin_platformswidget/generated/GeneratedRectangle9Widget8.dart';
import 'package:flutterapp/car_appapp/generatedlogin_platformswidget/generated/GeneratedORWidget.dart';
import 'package:flutterapp/car_appapp/generatedlogin_platformswidget/generated/GeneratedGoogle_loginWidget.dart';
import 'package:flutterapp/car_appapp/generatedlogin_platformswidget/generated/GeneratedLogin_textWidget.dart';
import 'package:flutterapp/car_appapp/generatedlogin_platformswidget/generated/GeneratedCREATEACCOUNTWidget.dart';
import 'package:flutterapp/car_appapp/generatedlogin_platformswidget/generated/GeneratedCOURTOFAPPEALREPORTSNIGERIAWidget1.dart';
import 'package:flutterapp/car_appapp/generatedlogin_platformswidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/car_appapp/generatedlogin_platformswidget/generated/GeneratedLogosfacebookWidget.dart';
import 'package:flutterapp/car_appapp/generatedlogin_platformswidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/car_appapp/generatedlogin_platformswidget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/car_appapp/generatedlogin_platformswidget/generated/GeneratedLogo_loginWidget.dart';
import 'package:flutterapp/car_appapp/generatedlogin_platformswidget/generated/GeneratedStatusbarWidget11.dart';
import 'package:flutterapp/car_appapp/generatedlogin_platformswidget/generated/GeneratedFacebook_loginWidget.dart';

/* Frame login_platforms
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogin_platformsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 247, 247, 247),
                      ),
                    ),
                    Positioned(
                      left: -3.0,
                      top: -5.0,
                      right: null,
                      bottom: null,
                      width: 382.0,
                      height: 332.08526611328125,
                      child: GeneratedRectangle2Widget(),
                    ),
                    Positioned(
                      left: -3.0,
                      top: 221.0,
                      right: null,
                      bottom: null,
                      width: 382.0,
                      height: 764.0,
                      child: GeneratedRectangle1Widget(),
                    ),
                    Positioned(
                      left: 31.0,
                      top: 229.0,
                      right: null,
                      bottom: null,
                      width: 280.0,
                      height: 68.08287048339844,
                      child: GeneratedLogin_textWidget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.6586666666666666;

                        final double height =
                            constraints.maxHeight * 0.08790710524385198;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.17066666666666666,
                              y: constraints.maxHeight * 0.11822660098522167,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child:
                                    GeneratedCOURTOFAPPEALREPORTSNIGERIAWidget1(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 19.0,
                      top: 400.0,
                      right: null,
                      bottom: null,
                      width: 337.0,
                      height: 61.62285232543945,
                      child: GeneratedGoogle_loginWidget(),
                    ),
                    Positioned(
                      left: 19.0,
                      top: 490.0,
                      right: null,
                      bottom: null,
                      width: 337.0,
                      height: 61.62285232543945,
                      child: GeneratedFacebook_loginWidget(),
                    ),
                    Positioned(
                      left: 48.0,
                      top: 501.0,
                      right: null,
                      bottom: null,
                      width: 32.0,
                      height: 32.0,
                      child: GeneratedLogosfacebookWidget(),
                    ),
                    Positioned(
                      left: 51.0,
                      top: 583.0,
                      right: null,
                      bottom: null,
                      width: 265.0,
                      height: 59.0,
                      child: GeneratedLogo_loginWidget(),
                    ),
                    Positioned(
                      left: 39.0,
                      top: 700.0,
                      right: null,
                      bottom: null,
                      width: 303.0,
                      height: 1.0,
                      child: GeneratedLine3Widget(),
                    ),
                    Positioned(
                      left: 141.0,
                      top: 658.0,
                      right: null,
                      bottom: null,
                      width: 89.0,
                      height: 33.0,
                      child: GeneratedORWidget(),
                    ),
                    Positioned(
                      left: 117.0,
                      top: 726.0,
                      right: null,
                      bottom: null,
                      width: 141.0,
                      height: 26.0,
                      child: GeneratedCREATEACCOUNTWidget(),
                    ),
                    Positioned(
                      left: 120.0,
                      top: 803.0,
                      right: null,
                      bottom: null,
                      width: 135.0,
                      height: 5.0,
                      child: GeneratedRectangle9Widget8(),
                    )
                  ]),
            ),
            Positioned(
              left: 20.0,
              top: 12.0,
              right: null,
              bottom: null,
              width: 340.0467834472656,
              height: 24.0,
              child: GeneratedStatusbarWidget11(),
            )
          ]),
    ));
  }
}
