import 'package:flutter/material.dart';
import 'package:flutterapp/car_appapp/generatedwelcome_screen4widget/generated/GeneratedIcsharpnextweekWidget3.dart';
import 'package:flutterapp/car_appapp/generatedwelcome_screen4widget/generated/GeneratedReadandResearchontheGoQualityreadonthegoforthefastpaced.dart';
import 'package:flutterapp/car_appapp/generatedwelcome_screen4widget/generated/GeneratedPagesbuttonWidget3.dart';
import 'package:flutterapp/car_appapp/generatedwelcome_screen4widget/generated/GeneratedStatusbarWidget4.dart';
import 'package:flutterapp/car_appapp/generatedwelcome_screen4widget/generated/GeneratedRead_on_the_goWidget.dart';
import 'package:flutterapp/car_appapp/generatedwelcome_screen4widget/generated/GeneratedRectangle9Widget4.dart';

/* Frame welcome_screen4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcome_screen4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedWelcome_screen5Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Container(
                width: 375.0,
                height: 812.0,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    overflow: Overflow.visible,
                    children: [
                      ClipRRect(
                        borderRadius: BorderRadius.zero,
                        child: Container(
                          color: Color.fromARGB(255, 247, 247, 247),
                        ),
                      ),
                      Positioned(
                        left: 62.0,
                        top: 277.0,
                        right: null,
                        bottom: null,
                        width: 255.2581787109375,
                        height: 549.0,
                        child:
                            GeneratedReadandResearchontheGoQualityreadonthegoforthefastpaced(),
                      ),
                      Positioned(
                        left: 66.0,
                        top: 652.0,
                        right: null,
                        bottom: null,
                        width: 245.0,
                        height: 21.0,
                        child: GeneratedPagesbuttonWidget3(),
                      ),
                      Positioned(
                        left: 163.0,
                        top: 726.0,
                        right: null,
                        bottom: null,
                        width: 50.0,
                        height: 50.0,
                        child: GeneratedIcsharpnextweekWidget3(),
                      ),
                      Positioned(
                        left: 39.0,
                        top: 154.0,
                        right: null,
                        bottom: null,
                        width: 297.0,
                        height: 287.5335693359375,
                        child: GeneratedRead_on_the_goWidget(),
                      ),
                      Positioned(
                        left: 120.0,
                        top: 797.0,
                        right: null,
                        bottom: null,
                        width: 135.0,
                        height: 5.0,
                        child: GeneratedRectangle9Widget4(),
                      )
                    ]),
              ),
              Positioned(
                left: 20.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 340.0467834472656,
                height: 24.0,
                child: GeneratedStatusbarWidget4(),
              )
            ]),
      ),
    ));
  }
}
