import 'package:flutter/material.dart';
import 'package:flutterapp/car_appapp/generatedbuttonwidget2/generated/GeneratedGETSTARTEDWidget1.dart';
import 'package:flutterapp/car_appapp/generatedbuttonwidget2/generated/GeneratedNextWidget2.dart';

/* Group button
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedButtonWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 230.0,
      height: 46.21210479736328,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 230.0,
              height: 45.0,
              child: GeneratedNextWidget2(),
            ),
            Positioned(
              left: 29.0,
              top: 0.25250244140625,
              right: null,
              bottom: null,
              width: 184.0,
              height: 47.95960235595703,
              child: GeneratedGETSTARTEDWidget1(),
            )
          ]),
    ));
  }
}
