import 'package:flutter/material.dart';
import 'package:flutterapp/car_appapp/generatedwelcome_screen3widget/generated/GeneratedCarhardcopyWidget.dart';
import 'package:flutterapp/car_appapp/generatedwelcome_screen3widget/generated/GeneratedStatusbarWidget3.dart';
import 'package:flutterapp/car_appapp/generatedwelcome_screen3widget/generated/GeneratedRectangle9Widget3.dart';
import 'package:flutterapp/car_appapp/generatedwelcome_screen3widget/generated/GeneratedHardCopyReportVolumes1122015tilldateoftheHardcopytextso.dart';
import 'package:flutterapp/car_appapp/generatedwelcome_screen3widget/generated/GeneratedIcsharpnextweekWidget2.dart';
import 'package:flutterapp/car_appapp/generatedwelcome_screen3widget/generated/GeneratedPagesbuttonWidget2.dart';

/* Frame welcome_screen3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcome_screen3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedWelcome_screen4Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Container(
                width: 375.0,
                height: 812.0,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    overflow: Overflow.visible,
                    children: [
                      ClipRRect(
                        borderRadius: BorderRadius.zero,
                        child: Container(
                          color: Color.fromARGB(255, 247, 247, 247),
                        ),
                      ),
                      Positioned(
                        left: 62.0,
                        top: 274.0,
                        right: null,
                        bottom: null,
                        width: 255.2581787109375,
                        height: 549.0,
                        child:
                            GeneratedHardCopyReportVolumes1122015tilldateoftheHardcopytextso(),
                      ),
                      Positioned(
                        left: 66.0,
                        top: 652.0,
                        right: null,
                        bottom: null,
                        width: 245.0,
                        height: 21.0,
                        child: GeneratedPagesbuttonWidget2(),
                      ),
                      Positioned(
                        left: 163.0,
                        top: 726.0,
                        right: null,
                        bottom: null,
                        width: 50.0,
                        height: 50.0,
                        child: GeneratedIcsharpnextweekWidget2(),
                      ),
                      Positioned(
                        left: 41.0,
                        top: 155.0,
                        right: null,
                        bottom: null,
                        width: 294.0,
                        height: 304.7966613769531,
                        child: GeneratedCarhardcopyWidget(),
                      ),
                      Positioned(
                        left: 120.0,
                        top: 797.0,
                        right: null,
                        bottom: null,
                        width: 135.0,
                        height: 5.0,
                        child: GeneratedRectangle9Widget3(),
                      )
                    ]),
              ),
              Positioned(
                left: 20.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 340.0467834472656,
                height: 24.0,
                child: GeneratedStatusbarWidget3(),
              )
            ]),
      ),
    ));
  }
}
