import 'package:flutter/material.dart';
import 'package:flutterapp/car_appapp/generatedregister_screenwidget/generated/GeneratedBack_loginWidget.dart';
import 'package:flutterapp/car_appapp/generatedregister_screenwidget/generated/GeneratedCreatebackWidget.dart';
import 'package:flutterapp/car_appapp/generatedregister_screenwidget/generated/GeneratedTcWidget.dart';
import 'package:flutterapp/car_appapp/generatedregister_screenwidget/generated/GeneratedButtonWidget.dart';
import 'package:flutterapp/car_appapp/generatedregister_screenwidget/generated/GeneratedEntry_linesWidget.dart';
import 'package:flutterapp/car_appapp/generatedregister_screenwidget/generated/GeneratedStatusbarWidget6.dart';
import 'package:flutterapp/car_appapp/generatedregister_screenwidget/generated/GeneratedIphonekeyboard1Widget.dart';

/* Frame register_screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegister_screenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 247, 247, 247),
                      ),
                    ),
                    Positioned(
                      left: 17.0,
                      top: 87.0,
                      right: null,
                      bottom: null,
                      width: 199.0,
                      height: 32.0,
                      child: GeneratedCreatebackWidget(),
                    ),
                    Positioned(
                      left: 27.0,
                      top: 169.0,
                      right: null,
                      bottom: null,
                      width: 324.0,
                      height: 106.0,
                      child: GeneratedEntry_linesWidget(),
                    ),
                    Positioned(
                      left: 64.0,
                      top: 345.0,
                      right: null,
                      bottom: null,
                      width: 247.0,
                      height: 43.0,
                      child: GeneratedButtonWidget(),
                    ),
                    Positioned(
                      left: 27.0,
                      top: 282.0,
                      right: null,
                      bottom: null,
                      width: 310.0,
                      height: 37.0,
                      child: GeneratedTcWidget(),
                    ),
                    Positioned(
                      left: 100.0,
                      top: 393.0,
                      right: null,
                      bottom: null,
                      width: 182.0,
                      height: 16.0,
                      child: GeneratedBack_loginWidget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 525.0,
                      right: null,
                      bottom: null,
                      width: 376.0,
                      height: 288.3575439453125,
                      child: GeneratedIphonekeyboard1Widget(),
                    )
                  ]),
            ),
            Positioned(
              left: 20.0,
              top: 12.0,
              right: null,
              bottom: null,
              width: 340.0467834472656,
              height: 24.0,
              child: GeneratedStatusbarWidget6(),
            )
          ]),
    ));
  }
}
