import 'package:flutter/material.dart';
import 'package:flutterapp/car_appapp/generatedlogin_screenwidget/generated/GeneratedStatusbarWidget7.dart';
import 'package:flutterapp/car_appapp/generatedlogin_screenwidget/generated/GeneratedEntry_linesWidget1.dart';
import 'package:flutterapp/car_appapp/generatedlogin_screenwidget/generated/GeneratedCreatebackWidget1.dart';
import 'package:flutterapp/car_appapp/generatedlogin_screenwidget/generated/GeneratedBack_loginWidget1.dart';
import 'package:flutterapp/car_appapp/generatedlogin_screenwidget/generated/GeneratedTcWidget1.dart';
import 'package:flutterapp/car_appapp/generatedlogin_screenwidget/generated/GeneratedButtonWidget1.dart';
import 'package:flutterapp/car_appapp/generatedlogin_screenwidget/generated/GeneratedIphonekeyboard1Widget1.dart';

/* Frame login_screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogin_screenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 247, 247, 247),
                      ),
                    ),
                    Positioned(
                      left: 17.0,
                      top: 87.0,
                      right: null,
                      bottom: null,
                      width: 97.0,
                      height: 32.0,
                      child: GeneratedCreatebackWidget1(),
                    ),
                    Positioned(
                      left: 27.0,
                      top: 169.0,
                      right: null,
                      bottom: null,
                      width: 324.0,
                      height: 106.0,
                      child: GeneratedEntry_linesWidget1(),
                    ),
                    Positioned(
                      left: 64.0,
                      top: 342.0,
                      right: null,
                      bottom: null,
                      width: 247.0,
                      height: 41.87214660644531,
                      child: GeneratedButtonWidget1(),
                    ),
                    Positioned(
                      left: 26.0,
                      top: 284.0,
                      right: null,
                      bottom: null,
                      width: 127.0,
                      height: 19.0,
                      child: GeneratedTcWidget1(),
                    ),
                    Positioned(
                      left: 100.0,
                      top: 390.0,
                      right: null,
                      bottom: null,
                      width: 182.0,
                      height: 16.0,
                      child: GeneratedBack_loginWidget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 525.0,
                      right: null,
                      bottom: null,
                      width: 376.0,
                      height: 288.3575439453125,
                      child: GeneratedIphonekeyboard1Widget1(),
                    )
                  ]),
            ),
            Positioned(
              left: 20.0,
              top: 12.0,
              right: null,
              bottom: null,
              width: 340.0467834472656,
              height: 24.0,
              child: GeneratedStatusbarWidget7(),
            )
          ]),
    ));
  }
}
