import 'package:flutter/material.dart';
import 'package:flutterapp/car_appapp/generatedsplashscreenwidget/generated/GeneratedCarlogoWidget.dart';
import 'package:flutterapp/car_appapp/generatedsplashscreenwidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/car_appapp/generatedsplashscreenwidget/generated/GeneratedStatusbarWidget.dart';

/* Frame splash screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedWelcome_screen1Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Container(
                width: 375.0,
                height: 812.0,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    overflow: Overflow.visible,
                    children: [
                      ClipRRect(
                        borderRadius: BorderRadius.zero,
                        child: Container(
                          color: Color.fromARGB(255, 247, 247, 247),
                        ),
                      ),
                      Positioned(
                        left: 75.0,
                        top: 268.0,
                        right: null,
                        bottom: null,
                        width: 226.0,
                        height: 275.0,
                        child: GeneratedCarlogoWidget(),
                      ),
                      Positioned(
                        left: 120.0,
                        top: 796.0,
                        right: null,
                        bottom: null,
                        width: 135.0,
                        height: 5.0,
                        child: GeneratedRectangle9Widget(),
                      )
                    ]),
              ),
              Positioned(
                left: 20.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 340.0467834472656,
                height: 24.0,
                child: GeneratedStatusbarWidget(),
              )
            ]),
      ),
    ));
  }
}
